New feature
NasirSethe/HELLO-PROJECT-ONE pull request #1
Opened 2023-03-21 18:44 UTC by NasirSethe

- The first step was to create a repository on GitHub. Next was the cloning of the repo to get a local directory then using the terminal I created a branch to work on. 

- This was followed by creating a HTML with a text "Hello Microverse!" and a CSS file to edit the text. Committed the changes on the terminal. The changes in each files were then committed to local repository separately.

- Next proceeded to setup the linter for HTML and CSS. Some errors showed in the CSS code and corrected the errors after some tries. Then I added a test.md file that was also added to the list of files to be ignored.

- Next the README file template was to be added to the list of files and later edited to fit the project. Some files like the MIT.md file were also part of the new additions in this step.

After committing the changes on the terminal at different stages of the project the final step was to push to the github repo.
Later created a pull request to kindly submit the project for a review.

2023-03-21 19:26 UTC, levy002 requested changes
## Hello @NasirSethe   , :wave:
### I'm Levy, your PR reviewer

Good job so far :+1: 
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif)

## Highlights
- Descriptive PR description :heavy_check_mark: 

## Status: REQUIRED CHANGES ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- [OPTIONAL] Kindly make sure next time to capitalize your commit messages. Please check this [lesson](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md) to understand it clearly.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @levy002 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-21 19:26 UTC, levy002 commented on README.md
> + [http://127.0.0.1:5500/index.html]
- [ ] Kindly make sure to remove this link because you presented it as the Live Demo version but it is not. You can do something like `LIVE DEMO COMING SOON` in order to let the repository visitor know the current status instead of adding a localhost link that doesn't show anything.

2023-03-21 19:26 UTC, levy002 commented on README.md
> +
- [ ] KIndly make sure to adjust your README because the last big part looks like a suggestion which is totally wrong. I think you have left a big empty space at the start of those sections. Kindly fix that.

2023-03-21 19:26 UTC, levy002 commented on github/workflows/linters.yml
> +          if [ -d "node_modules/" ]; then echo -e "\e[1;31mThe node_modules/ folder was pushed to the repo. Please remove it from the GitHub repository and try again."; echo -e "\e[1;32mYou can set u
- [ ] Kindly make sure Linters are running correctly so it checks if there are no errors on your pull request. I recommend you take a step back and read this[ lesson](https://github.com/microverseinc/linters-config/blob/master/html-css) to understand it clearly and follow the guideline to set it correctly.

   - ### YOUR GITHUB ACTIONS CHECK
   
     ![image](https://user-images.githubusercontent.com/87197412/226718470-21c70422-a031-406b-b40a-03f5f23ee43d.png)

   - ### CORRECT GITHUB ACTION CHECK
   
     ![image](https://user-images.githubusercontent.com/87197412/226644400-de7f52c4-ef4c-444d-9276-abf12d3404dd.png)

2023-03-21 19:31 UTC, NasirSethe commented on README.md
> + [http://127.0.0.1:5500/index.html]
@levy002  noted with thanks. Will make the necessary changes here.

2023-03-21 19:36 UTC, NasirSethe commented on README.md
> +
@levy002 Hi Levy, do you mean the spaces in line 97/98/99/100 for example? I should delete those lines and bring the content a little closer to each other correct if I understood wrong please?

2023-03-21 19:55 UTC, NasirSethe commented on github/workflows/linters.yml
> +          if [ -d "node_modules/" ]; then echo -e "\e[1;31mThe node_modules/ folder was pushed to the repo. Please remove it from the GitHub repository and try again."; echo -e "\e[1;32mYou can set u
@levy002  thank you . will resolve this issue right away.

2023-03-21 19:58 UTC, levy002 commented on README.md
> +
Hello, @NasirSethe, that is what I think I think is causing a problem but make sure your README looks like the given README template.

 ### YOUR README HOW IT LOOKS
   ![image](https://user-images.githubusercontent.com/87197412/226726104-bcc7bab1-c390-44cd-944e-90388c77c0f6.png)

### README TEMPLATE

   ![image](https://user-images.githubusercontent.com/87197412/226726505-5bc3dc3f-6292-40f3-afca-91d0d607b6b3.png)

2023-03-22 13:28 UTC, NasirSethe commented
@levy002 Hi Levy, made the necessary changes, kindly take a look at the readme file and the the checks for linters that have been corrected. Thank you!

2023-03-22 13:41 UTC, bobb-Rob requested changes
## STATUS: CHANGES REQUIRED ♻️

Hi @NasirSethe, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![](https://camo.githubusercontent.com/34482800e1b92cb79ddca06edb4051edc407cb190f896e1e949e596aa9073851/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966)

 ## Highlights
✅ No Linter error
✅ Correct use of GitHub flow
✅ Very descriptive Pull Request(PR)

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-22 13:41 UTC, bobb-Rob commented on README.md
> +<p align="right">(<a href="#readme-top">back to top</a>)</p>
- [ ] I noticed that your README file is missing most of the sections. Please take a closer look at the provided README template and copy it exactly as it is. The only optional section is the FAQ section, all other sections are compulsory and must be edited with the right text to suit this project. Please note that this is essential for all other projects you will complete in Microverse.

You can use[ this project](https://github.com/KenbonTN/Hello-Microverse-1/tree/feature-branch) as a guide to edit your readme

Your README
---- |
![image](https://user-images.githubusercontent.com/84156714/226921363-3aa33c8c-b705-4ecd-90b6-67af3bb36a55.png) 

 Microverse README
---- |
![image](https://user-images.githubusercontent.com/84156714/226922026-c65b3f87-d161-460f-92bc-69f421ae2341.png)

2023-03-22 16:50 UTC, NasirSethe commented on README.md
> +<p align="right">(<a href="#readme-top">back to top</a>)</p>
@bobb-Rob  Thank you very much for your valuable input and will attend to the changes immediately!

2023-03-22 17:09 UTC, NasirSethe commented
@braincee Much appreciated!!!👏👏👏 Thank you for your time!

2023-03-22 17:09 UTC, merged